# DEV ONLY
FROM node:20-alpine

WORKDIR /app


ENV CHOKIDAR_USEPOLLING=true


ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

COPY package.json package-lock.json* ./
RUN npm ci


EXPOSE 5173


CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
