version: "3.9"

services:
  db:
    image: mysql:8
    container_name: kira_db
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kira_backend
    environment:
      # "db"
      DATABASE_URL: mysql+pymysql://app:app@db:3306/app_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000/kiraINV/
    container_name: kira_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
